using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluentKit.IconGenerator;

/// <summary>
/// Generates <c>FluentIconNames.g.cs</c> — one <c>const string</c> per glyph found in
/// wwwroot/Icons/FluentSystemIcons-Regular.css — as a second partial of
/// <c>FluentKit.Primitives.FluentIconNames</c>. Runs automatically at build time, so the
/// constants stay in sync whenever the Fluent System Icons font is upgraded; no script to
/// remember to re-run.
///
/// To pick up the CSS file, FluentKit.csproj must expose it as an AdditionalFile, e.g.:
/// <code>
/// &lt;ItemGroup&gt;
///   &lt;AdditionalFiles Include="wwwroot/Icons/FluentSystemIcons-Regular.css" /&gt;
/// &lt;/ItemGroup&gt;
/// </code>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FluentIconNamesGenerator : IIncrementalGenerator
{
    private static readonly Regex ClassRegex = new(
        @"\.icon-(ic_fluent_[a-z0-9_]+_regular)\s*:before",
        RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var cssFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(
                "FluentSystemIcons-Regular.css", StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(cssFiles, static (spc, file) =>
        {
            var text = file.GetText(spc.CancellationToken);
            if (text is null)
            {
                return;
            }

            var source = Generate(text, file.Path, spc);
            if (source is not null)
            {
                spc.AddSource("FluentIconNames.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? Generate(SourceText css, string path, SourceProductionContext spc)
    {
        var glyphs = ClassRegex.Matches(css.ToString())
            .Cast<Match>()
            .Select(m => m.Groups[1].Value)
            .Distinct()
            .OrderBy(g => g, StringComparer.Ordinal)
            .ToList();

        if (glyphs.Count == 0)
        {
            spc.ReportDiagnostic(Diagnostic.Create(NoGlyphsFound, Location.None, path));
            return null;
        }

        var entries = new List<(string ConstName, string Glyph)>();
        var seen = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var glyph in glyphs)
        {
            var constName = ConstNameFor(glyph);

            if (seen.TryGetValue(constName, out var existingGlyph))
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    NameCollision, Location.None, constName, existingGlyph, glyph));
                continue;
            }

            seen[constName] = glyph;
            entries.Add((constName, glyph));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by FluentKit.IconGenerator from wwwroot/Icons/FluentSystemIcons-Regular.css.");
        sb.AppendLine("// Do not edit by hand — this file regenerates on every build.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("namespace FluentKit.Primitives;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Compile-time-checked constants for every glyph in");
        sb.AppendLine("/// wwwroot/Icons/FluentSystemIcons-Regular.css, for use with");
        sb.AppendLine("/// <see cref=\"FluentIcon.Name\"/>. Constant names are the glyph's words in");
        sb.AppendLine("/// PascalCase followed by its pixel size, e.g. <c>AccessTime24</c> for");
        sb.AppendLine("/// <c>ic_fluent_access_time_24_regular</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class FluentIconNames");
        sb.AppendLine("{");

        foreach (var (constName, glyph) in entries)
        {
            sb.AppendLine($"    public const string {constName} = \"{glyph}\";");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ConstNameFor(string glyph)
    {
        // glyph looks like: ic_fluent_access_time_24_regular
        const string prefix = "ic_fluent_";
        const string suffix = "_regular";

        var middle = glyph.Substring(prefix.Length, glyph.Length - prefix.Length - suffix.Length);
        var parts = middle.Split('_');

        var size = parts[parts.Length - 1];
        var nameParts = parts.Take(parts.Length - 1);

        var name = string.Concat(nameParts.Select(Pascal)) + size;

        return char.IsDigit(name[0]) ? "Icon" + name : name;
    }

    private static string Pascal(string word)
    {
        if (word.Length == 0 || char.IsDigit(word[0]))
        {
            return word;
        }

        return char.ToUpperInvariant(word[0]) + word.Substring(1);
    }

    private static readonly DiagnosticDescriptor NameCollision = new(
        id: "FLKICON001",
        title: "Duplicate generated icon constant name",
        messageFormat: "Constant name '{0}' was generated for both '{1}' and '{2}'; the second glyph was skipped",
        category: "FluentKit.IconGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoGlyphsFound = new(
        id: "FLKICON002",
        title: "No icon glyphs found",
        messageFormat: "No '.icon-ic_fluent_..._regular' classes were found in '{0}'; check the CSS format hasn't changed",
        category: "FluentKit.IconGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
}